# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: erp_cat
  host: localhost
  port: 5432
  username: egusquiza31
  password: "ajugardota2"

test:
  <<: *default
  database: erp_cat_test
  host: localhost
  port: 5432
  # username: <%= ENV["DATA_BASE_USER_NAME"] %>
  # password: <%= ENV["DATA_BASE_USER_PASSWORD"] %>
  username: tefa
  password: "0203"

production:
  <<: *default
  database: erp_cat_production
  username: backend
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>

replica:
  <<: *default
  database: erp_cat_replica
  host: localhost
  port: 5432
  username: tefa
  password: "0203"
